require "import"
import "util.m3-import"
import "util.color"
return
{
  LinearLayout;
  layout_width="fill";
  layout_height="wrap_content";
  {
    MaterialCardView;
    layout_width="match_parent";
    id="下载关卡",
    layout_height="wrap_content";
    layout_marginBottom="10dp";
    layout_marginLeft="10dp";
    --StrokeColor=0,
    StrokeColor=colorOnSecondaryContainer,
    layout_marginRight="10dp";
    {
      LinearLayout;
      padding="10dp";
      layout_width="match_parent";
      layout_height="wrap_content";
      {
        ImageView;
        layout_gravity="center";
        layout_height="40dp";
        src="res/rsr.png",
        layout_width="40dp";
      };
      {
        LinearLayout;
        orientation="vertical";
        layout_height="wrap_content";
        gravity="left|center";
        layout_marginLeft="10dp";
        {
          TextView;
          layout_gravity="left|center";
          text="LevelName";
          textSize="20sp";
          id="level1";
        };
        {
          TextView;
          layout_gravity="left|center";
          text="Author";
          id="author1";
        };
      };
    };
  };
};