require "import"
import "util.m3-import"
import "util.color"
return
{
  LinearLayout;
  layout_width="fill";
  layout_height="wrap_content";
  {
    MaterialCardView;
    layout_width="match_parent";
    id="Tools",
    layout_height="wrap_content";
    layout_marginLeft="10dp";
    StrokeColor=0,
    layout_marginRight="10dp";
    {
      LinearLayout;
      padding="10dp";
      layout_width="match_parent";
      layout_height="wrap_content";
      {MaterialCardView;
        layout_height="45dp";
        layout_width="45dp";
        radius="80",
      {
        ImageView;
        layout_gravity="center";
        layout_height="fill";
        layout_width="fill";
        id="ToolsImage",
      };
    };
      {
        LinearLayout;
        orientation="vertical";
        layout_height="wrap_content";
        gravity="left|center";
        layout_marginLeft="10dp";
        {
          TextView;
          layout_gravity="left|center";
          text="Name";
          textSize="20sp";
          id="ToolsName";
        };
        {
          TextView;
          layout_gravity="left|center";
          text="Text";
          id="ToolsText";
        };
      };
    };
  };
};